version: "3.6"
services:
    git-server:
      build:
        dockerfile: git-server/Dockerfile
        context: .
      container_name: git-server
      restart: always
      ports:
        - "22:22"
      volumes:
        - "./repo_keys:/git-server/keys"
        - "repos:/git-server/repos"
    create-repo:
      depends_on: 
        - git-server
      build:
        dockerfile: create-repo/Dockerfile
        context: .
      container_name: create-repo
      volumes:
        - "repos:/git-server/repos"
volumes:
  repos: