version: "3.6"
services:
  git-server:
    extends:
      service: git-server
      file: docker-compose.yaml
    networks:
    - default
networks:
  default:
    external: true
    name: vsc-helm-repo-updater-network