name: Tests

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: golangci/golangci-lint-action@v2
        with:
          version: v1.40.1
  
  tests:
    name: Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-go@v2
        with:
          go-version: 1.17

      - run: make build

      - run: make launch-test-deps

      - run: make test
