name: Tests

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: golangci/golangci-lint-action@v2
        with:
          version: v1.40.1
  
  tests:
    name: Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-go@v2
        with:
          go-version: 1.17

      - name: Set SSH_PRIVATE_KEY
        run: echo '::set-output name=SSH_PRIVATE_KEY::$(cat test-git-server/private_keys/helm-repo-updater-test)'
        id: set-ssh-private-key

      - uses: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-key: ${{ steps.set-ssh-private-key.outputs.SSH_PRIVATE_KEY }}

      - run: make build

      - run: make test
