name: Tests

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: golangci/golangci-lint-action@v2
        with:
          version: v1.40.1
  
  tests:
    name: Tests
    runs-on: ubuntu-latest
    container: 
      image: ghcr.io/docplanner/helm-repo-updater/build-tools:develop
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.CR_PAT }}
    # Service containers to run with `container-job`
    services:
      # Label used to access the service container
      git-server:
        image: ghcr.io/docplanner/helm-repo-updater/git-repo-server:develop
        ports:
          - 2222:22
        credentials:
          username: ${{ github.actor }}
          password: ${{ secrets.CR_PAT }}
    steps:
      - uses: actions/checkout@v2

      # - uses: actions/setup-go@v2
      #   with:
      #     go-version: 1.17

      - run: make build

      - name: try clone repository
        run: |
          eval $(ssh-agent)
          chmod 600 test-git-server/private_keys/helm-repo-updater-test
          ssh-add test-git-server/private_keys/helm-repo-updater-test
          git clone ssh://git@git-server/git-server/repos/test-repo.git /tmp/test-repo -v

      # - run: make test
      - name: run tests
        run: go test  -covermode=atomic -coverpkg=./... ./...
