name: Tests

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: golangci/golangci-lint-action@v2
        with:
          version: v1.40.1
  
  tests:
    name: Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-go@v2
        with:
          go-version: 1.17

      - name: View all in port 22
        run: |
          sudo lsof -i -P -n | grep 22
          sudo lsof -i:22

      - name: Kill all in port 22
        run: |
          sudo fuser -k 22/tcp
          sudo fuser -k 22/tcp4

      - name: Create git-repo-server and repository with docker
        run: bash launch_test_env.sh "create"

      - run: make build

      - run: make test
