name: Tests

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: golangci/golangci-lint-action@v2
        with:
          version: v1.40.1
  
  tests:
    name: Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-go@v2
        with:
          go-version: 1.17

      # - name: Get SSH_PRIVATE_KEY
      #   id: get_ssh_private_key
      #   run: |
      #     echo SSH_PRIVATE_KEY=$(cat test-git-server/private_keys/helm-repo-updater-test)>> $GITHUB_ENV

      # - name: Configure SSH_PRIVATE_KEY
      #   uses: webfactory/ssh-agent@v0.5.4
      #   with:
      #     ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Configure SSH_PRIVATE_KEY
        run: |
          chmod 600 test-git-server/private_keys/helm-repo-updater-test
          ssh-add test-git-server/private_keys/helm-repo-updater-test

      - run: make build

      - run: make test
