name: Tests

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize

jobs:
  static-checks:
    name: Static Checks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2.3.1
        with:
          python-version: '3.9'
      - uses: actions/setup-go@v2
        with:
          go-version: 1.17
      - name: Get golangci
        run: curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v${GOLANGCI_LINT_VERSION}
        env:
          GOLANGCI_LINT_VERSION: "1.44.0"
      - name: Check golangci-lint installation
        run: golangci-lint --version
      - uses: pre-commit/action@v2.0.3

  unit-tests:
    name: Unit Tests
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/docplanner/helm-repo-updater/build-tools:develop
      # TODO: Remind to delete this part when we make public the repository
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.CR_PAT }}
    services:
      git-server:
        image: ghcr.io/docplanner/helm-repo-updater/git-repo-server:develop
        # TODO: Remind to delete this part when we make public the repository
        credentials:
          username: ${{ github.actor }}
          password: ${{ secrets.CR_PAT }}
    steps:
      - uses: actions/checkout@v2

      - run: make build

      - run: make test-coverage
        env:
          isCI: true
