name: Tests

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize

jobs:
  static-checks:
    name: Static Checks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Configure python
        uses: actions/setup-python@v2.3.1
        with:
          python-version: '3.9'
      - name: Configure Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17
      - name: Get golangci-lint
        run: curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v${GOLANGCI_LINT_VERSION}
        env:
          GOLANGCI_LINT_VERSION: "1.44.2"
      - name: Run pre-commit
        uses: pre-commit/action@v2.0.3

  unit-tests:
    name: Unit Tests
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/docplanner/helm-repo-updater/build-tools:develop
    services:
      git-server:
        image: ghcr.io/docplanner/helm-repo-updater/git-repo-server:develop
    steps:
      - uses: actions/checkout@v2

      - name: Build app
        run: make build

      - name: Launch unit tests
        run: make test-coverage
        env:
          isCI: true
          SSH_KNOWN_HOSTS: "/root/.ssh/known_hosts"
